### PR TITLE
Backporting "undefined reference to peg::enabler"

### PR DESCRIPTION
**Pull request by rkollataj**
Compilation using clang 3.5.2 results in an error fixed in #29. As the problem will probably exist in all clang versions older than v5 it may be better to change the check to include all older versions instead of adding another exact one (i.e. 3.5.2). Another minor fix enables tests to compile with clang 3.5.2 - without it lambda return type deduction fails.

Signed-off-by: Remigiusz Kołłątaj <remigiusz.kollataj@mobica.com>

### CODE REVIEW

**Comment by yhirose** [comment]
@rkollataj, it seems like [My recent change](https://github.com/yhirose/cpp-peglib/pull/38/files#diff-23ec54723a94d79182a91481d9dfc5cbL1957) in #38 is also related to the issue.
Thanks for finding the problem and fixing it!
